### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by fladd** [thomasf/solarized-css#12]
Hello,

I could not find a licence for this project and hence I am unsure about whether this code can be used in other projects. It would be great if this could be clarified.

Thanks!

**Comment by thomasf** [comment]
Feel free to do whatever you want. 
I've taken one small pull request moving a couple of lines, otherwise I've written it all.

**Comment by thomasf** [comment]
(I'll add the mit license file later.)

**Comment by fladd** [comment]
That's great news, thanks!
Your work is now featured here: https://github.com/fladd/stuffpages
